### ISSUE TITLE
DTLS support

### ISSUE THREAD

**Issue by ekarlso** [zubairhamed/betwixt#40]
Hi, any ideas on this?

**Comment by markrey** [comment]
+1
any updates on this ?

**Comment by zubairhamed** [comment]
Hi,

Sorry it took me a while to look at this since i was out of my home country for a while.
I'm working on at least a PresharedKey option now. 

Since this is based on my Go CoAP library, i'm fixing it there.

The branch is @ https://github.com/zubairhamed/canopus/tree/client-refactor+dtls

**Comment by zubairhamed** [comment]
DTLS with PSK implemented in Canopus with commit zubairhamed/canopus@ad1de684b531cf11adf7df7bd4b9b4a6cfe409d0

First to refactor the Betwixt codebase then add DTLS

**Comment by dtoubelis** [comment]
@zubairhamed Is there any progress on this? Can I help to expedite this work in any way? We are open to sponsoring development of this feature.
